# Generated by Django 4.2.11 on 2026-04-21 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_classroom_teacherprofile_studentprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='记录日期（那晚所属日期）')),
                ('bedtime', models.DateTimeField(blank=True, null=True, verbose_name='入睡时间')),
                ('wake_time', models.DateTimeField(blank=True, null=True, verbose_name='起床时间')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='睡眠时长(分钟)')),
                ('subjective_score', models.PositiveSmallIntegerField(default=3, verbose_name='主观评分(1-5)')),
                ('quality_score', models.PositiveSmallIntegerField(default=0, verbose_name='质量分(0-100)')),
                ('status', models.CharField(choices=[('normal', '健康'), ('warning', '一般'), ('abnormal', '异常'), ('severe', '严重'), ('missed', '未打卡')], default='missed', max_length=16, verbose_name='状态')),
                ('mood_tag', models.CharField(blank=True, choices=[('great', '😄 极佳'), ('good', '🙂 良好'), ('normal', '😐 一般'), ('tired', '😪 疲惫'), ('bad', '😣 糟糕')], default='', max_length=16, verbose_name='心情')),
                ('diary', models.TextField(blank=True, default='', verbose_name='日记')),
                ('modified_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='修改原因')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_sleep_records', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to='users.studentprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '睡眠记录',
                'verbose_name_plural': '睡眠记录',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['status'], name='sleep_sleep_status_a092a9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sleeprecord',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='uniq_student_date'),
        ),
    ]
