# Generated by Django 4.2.11 on 2026-04-21 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='班级名称')),
                ('invite_code', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='班级邀请码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='班主任')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_no', models.CharField(max_length=32, unique=True, verbose_name='工号')),
                ('real_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '老师档案',
                'verbose_name_plural': '老师档案',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('real_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], default='O', max_length=2, verbose_name='性别')),
                ('grade', models.CharField(blank=True, default='', max_length=16, verbose_name='年级')),
                ('target_sleep_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=3, verbose_name='目标睡眠时长(小时)')),
                ('target_bedtime', models.TimeField(default='23:00', verbose_name='目标入睡时间')),
                ('risk_level', models.CharField(choices=[('normal', '正常'), ('focus', '重点关注')], default='normal', max_length=16, verbose_name='风险等级')),
                ('parent_invite_code', models.CharField(blank=True, db_index=True, default='', max_length=8, verbose_name='家长邀请码')),
                ('invite_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='邀请码过期时间')),
                ('share_diary_to_teacher', models.BooleanField(default=False, verbose_name='允许老师查看我的日记')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.classroom', verbose_name='班级')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学生档案',
                'verbose_name_plural': '学生档案',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('child', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profile', to='users.studentprofile', verbose_name='绑定的孩子')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '家长档案',
                'verbose_name_plural': '家长档案',
            },
        ),
    ]
