# Generated by Django 4.2.11 on 2026-04-21 08:23

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_classroom_teacherprofile_studentprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='target_bedtime',
            field=models.TimeField(default=apps.users.models._default_bedtime, verbose_name='目标入睡时间'),
        ),
    ]
