# Generated by Django 4.2.11 on 2026-04-21 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_classroom_teacherprofile_studentprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('manual', '手动触发'), ('auto', '自动触发')], default='manual', max_length=16, verbose_name='触发方式')),
                ('prompt_summary', models.CharField(blank=True, default='', max_length=512, verbose_name='数据摘要')),
                ('advice_text', models.TextField(verbose_name='AI 建议')),
                ('is_mock', models.BooleanField(default=False, verbose_name='Mock 兜底')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_advices', to='users.studentprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': 'AI 建议',
                'verbose_name_plural': 'AI 建议',
                'ordering': ['-created_at'],
            },
        ),
    ]
