# Generated by Django 4.2.11 on 2026-04-21 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_classroom_teacherprofile_studentprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='标识码')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('icon', models.CharField(blank=True, default='🏅', max_length=255, verbose_name='图标(emoji 或 URL)')),
            ],
            options={
                'verbose_name': '成就',
                'verbose_name_plural': '成就',
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='解锁时间')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='achievements.achievement', verbose_name='成就')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.studentprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生成就',
                'verbose_name_plural': '学生成就',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentachievement',
            constraint=models.UniqueConstraint(fields=('student', 'achievement'), name='uniq_student_achievement'),
        ),
    ]
